const placeholders = [
  'Eat a frog...',
  'Bake a cake...',
  'Win the lotto...',
  'Eat a taco...',
  'Wash the dog...',
  'Find the cat...',
  'Climb a mountain...',
  'Change the world...',
  'Build a house...',
  'Get a job...',
  'Destroy a dozen chickenwings...',
  'Hangout with a friend...',
  'Ask for a raise...',
  'Run three miles...',
  'Buy groceries...',
  'Don\'t offend anyone...',
  'Find my wallet...',
  'Survive the hangover...',
  'Apply to clown college...',
  'Become a dog walker...',
  'Discover Atlantis...',
  'Clean out the fridge...',
  'Read a book...',
  'Outsmart the telemarketer...',
  'Get a haircut...',
  'Go to the gym...',
  'Think like a cat...',
  'Go outside...',
  'Clean the car...',
  'Wish grandma a happy birthday...',
  'Eat your veggies...',
  'Talk to a stranger...',
  'Eat a balanced breakfast...',
  'Brush your teeth...',
  'Go to the doctor...',
  'Finish the project...',
  'Apply yourself, damnit!',
  'Drink a lot of water...',
  'Learn something new...',
  'Be thankful for the little things...',
  'Respect bedtime...',
  'Do that thing you hate...',
  'Do the laundry...',
  'Take your pills...',
  'Water the plants...',
  'Call Dad...',
  'Eat a salad...',
  'Meditate...',
  'Practice the ukulele...',
  'Volunteer...',
  'Dontate to charity...',
  'Do a handstand...',
  'Clap with one hand...',
  'Diffuse a bomb...',
  'Build a human pyramid...'

];

export default placeholders;